# ============================================================
# Inventory: datastore_create/inventories/vmware_hosts.yml
# Description:
#   Defines ESXi hosts for VMFS datastore creation.
#   Sensitive credentials are stored in group_vars/all.yml
#   encrypted with Ansible Vault.
# ============================================================
---
all:
  hosts:
    localhost:
      ansible_python_interpreter: /home/ansibleadmin/ansible-venv/bin/python
      esxi_hostname: "172.23.54.123"
      esxi_validate_certs: false
