---
# ###################################################################
# Example : VSP One Port Playbook
# Note - Verify the correct port ids are configured for your deployment
# Post playbook execution: run playbook day0_vsp_one_ports_facts.yml to confirm the updates
# ************************************************************************************************
# NOTE - B85 will use ports CL1-A, CL2-A, CL1-B, and CL2-B. Update the playbook when ready to test
# ************************************************************************************************
# ###################################################################
- name: VSP One Port Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    # ###################################################################
    # Task Name : Configure basic port settings (port security and speed)
    # ###################################################################
    - name: Configure basic port settings (port security and speed) CL1-A
      hitachivantara.vspone_block.vsp.hv_vsp_one_port:
        connection_info: "{{ connection_info }}"
        spec:
          port_id: "CL1-A"
          port_speed_in_gbps: 32
          enable_port_security: true

      register: result_cl1_a
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result_cl1_a

     # ###################################################################
    # Task Name : Configure basic port settings (port security and speed)
    # ###################################################################
    - name: Configure basic port settings (port security and speed) CL1-B
      hitachivantara.vspone_block.vsp.hv_vsp_one_port:
        connection_info: "{{ connection_info }}"
        spec:
          port_id: "CL1-B"
          port_speed_in_gbps: 32
          enable_port_security: true

      register: result_cl1_b
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result_cl1_b

     # ###################################################################
    # Task Name : Configure basic port settings (port security and speed)
    # ###################################################################
    - name: Configure basic port settings (port security and speed) CL1-A
      hitachivantara.vspone_block.vsp.hv_vsp_one_port:
        connection_info: "{{ connection_info }}"
        spec:
          port_id: "CL2-A"
          port_speed_in_gbps: 32
          enable_port_security: true

      register: result_cl2_a
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result_cl2_a

     # ###################################################################
    # Task Name : Configure basic port settings (port security and speed)
    # ###################################################################
    - name: Configure basic port settings (port security and speed) CL2-B
      hitachivantara.vspone_block.vsp.hv_vsp_one_port:
        connection_info: "{{ connection_info }}"
        spec:
          port_id: "CL2-B"
          port_speed_in_gbps: 32
          enable_port_security: true

      register: result_cl2_b
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result_cl2_b