---
######################################################################################
# Playbook : Create Pool on Secondary Storage
######################################################################################
- name: Storage Pool Creation - Secondary Storage
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var_6831.yml

  vars:
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ######################################################################################
    # Task 1 : Create a storage pool using required details
    ######################################################################################
    - name: Create storage pool on secondary storage
      hitachivantara.vspone_block.vsp.hv_storagepool:
        connection_info: "{{ connection_info }}"
        state: present
        spec:
          id: 25
          name: "Ansible-iSCSI-GAD"
          type: "HDP"
          pool_volumes:
            - parity_group_id: "1-1"
              capacity: "100GB"
      register: pool_result

    - name: Debug pool creation result
      ansible.builtin.debug:
        var: pool_result

