---
####################################################################
# Example : VSP One Port details 
####################################################################
- name: VSP One Port facts Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var_6827.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get port information by port ID
    ####################################################################
    - name: Get port information by port ID
      hitachivantara.vspone_block.vsp.hv_vsp_one_port_facts:
        connection_info: "{{ connection_info }}"
        spec:
          port_id: "CL2-D"

      register: result
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

