---
####################################################################
# Example :  Remote Storage RegistrationPlaybook
####################################################################
- name: Remote Storage Registration
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var_6827_6831.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ######################################################################################
    # Task Name : Register Remote Storage
    ######################################################################################
    - name: Register Remote Storage
      hitachivantara.vspone_block.vsp.hv_remote_storage_registration:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        state: present
        spec:
          rest_server_ip: "172.23.68.31"
          is_mutual_discovery: true
      register: result

    - name: Debug result
      ansible.builtin.debug:
        var: result
