---
####################################################################
# External Parity Group + External Path Group Playbook (Looped)
####################################################################
- name: External Parity Group and Path Group
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

    # Define lun_ids for each group
    lun_ids:
      2: 0
      3: 1
      4: 2
      5: 3
      6: 4
      7: 5
      8: 6
      9: 7

  tasks:
    ######################################################################
    # Task 1 : Create external parity groups (1-2 to 1-9)
    ######################################################################
    - name: Create external parity groups
      hitachivantara.vspone_block.vsp.hv_external_paritygroup:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          external_parity_group_id: "1-{{ item }}"
          external_path_group_id: "{{ item }}"
          port_id: "CL5-B"
          external_wwn: "50060e8008eb5020"
          lun_id: "{{ lun_ids[item] }}"
      loop: "{{ range(2,10) | list }}"
      register: parity_results

    - name: Debug parity group results
      ansible.builtin.debug:
        var: parity_results

    ######################################################################
    # Task 2 : Add external FC paths to external path groups (2 to 9)
    ######################################################################
    - name: Add external FC paths to external path groups
      hitachivantara.vspone_block.vsp.hv_external_path_group:
        connection_info: "{{ connection_info }}"
        state: "add_external_path"
        spec:
          external_path_group_id: "{{ item }}"
          external_fc_paths:
            - port: "CL5-B"
              external_wwn: "50060e8008eb5060"
            - port: "CL6-B"
              external_wwn: "50060e8008eb5020"
            - port: "CL6-B"
              external_wwn: "50060e8008eb5060"
            - port: "CL7-A"
              external_wwn: "50060e8008eb5012"
            - port: "CL7-A"
              external_wwn: "50060e8008eb5052"
            - port: "CL8-A"
              external_wwn: "50060e8008eb5012"
            - port: "CL8-A"
              external_wwn: "50060e8008eb5052"
      loop: "{{ range(2,10) | list }}"
      register: path_results

    - name: Debug path group results
      ansible.builtin.debug:
        var: path_results

