---
####################################################################
# Example : Hostgroup Playbook
####################################################################
- name: Hostgroup Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Create hostgroup
    ####################################################################
    - name: Create hostgroup
      hitachivantara.vspone_block.vsp.hv_hg:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "hg-B85-7A-8A"
          port: "CL6-C"
          host_mode: "WINDOWS_EXTENSION"
          #host_mode_options: []
          ldevs: [400, 401, 402, 403, 404, 405, 406, 407]
          wwns:
            - wwn: "50060e803411a560"
              nick_name: "7A_WWN1"
            - wwn: "50060e803411a570"
              nick_name: "8A_WWN2"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
