---
####################################################################
# Example : Hostgroup Playbook
####################################################################
- name: Hostgroup Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 1 : Create hostgroup on CL1-E
    ####################################################################
    - name: Create hostgroup on CL1-E
      hitachivantara.vspone_block.vsp.hv_hg:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "hg-B85-UVM-CL1E"
          port: "CL1-E"
          host_mode: "LINUX"
          ldevs: [14]
          wwns:
            - wwn: "21000024ff86a664"
              nick_name: "Host_WWN_CL1E"
      register: result_cl1e

    - name: Debug CL1-E result
      ansible.builtin.debug:
        var: result_cl1e

    ####################################################################
    # Task 2 : Create hostgroup on CL2-E
    ####################################################################
    - name: Create hostgroup on CL2-E
      hitachivantara.vspone_block.vsp.hv_hg:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "hg-B85-UVM-CL2E"
          port: "CL2-E"
          host_mode: "LINUX"
          ldevs: [14]
          wwns:
            - wwn: "21000024ff86a665"
              nick_name: "Host_WWN_CL2E"
      register: result_cl2e

    - name: Debug CL2-E result
      ansible.builtin.debug:
        var: result_cl2e

