---
######################################################################################
# Example :  Storage Pool Playbook
######################################################################################
- name: Storage Pool Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ######################################################################################
    # Task Name : Create a storage pool with a specific pool ID and LDEV numbers
    # Ensure the LDEVs specified in ldev_ids are in NML state and size of each LDEV
    # is greater than 8.0GB
    ######################################################################################
    - name: Create a storage pool with a specific pool ID and LDEV numbers
      hitachivantara.vspone_block.vsp.hv_storagepool:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          id: 9
          name: "UVM-Pool"
          type: "HDP"
          ldev_ids: [145, 146, 147, 148, 149, 150, 151]
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
