---
- name: Storage Pool Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ######################################################################################
    # Create a storage pool using required details
    ######################################################################################
    - name: Create a storage pool using required details
      hitachivantara.vspone_block.vsp.hv_storagepool:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "storagepool-test-ansible"
          type: "HDP"
          pool_volumes:
            - parity_group_id: "1-1"
              capacity: "50GB"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
