---
- name: GAD - Global Active Device Pair Management
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ####################################################################
    #Create GAD-NVMe Pair
    ####################################################################
    - name: Create GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        spec:
          copy_group_name: "copy_group_name_12"
          copy_pair_name: "copy_pair_name_12"

          primary_volume_id: 600
          secondary_pool_id: 17
          secondary_nvm_subsystem:
            name: ansible_nvm_subsystem
            paths:
              - "nqn.2014-08.com.vmware:nvme:gad-nvme-host"
          quorum_disk_id: 4

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

