---
- name: External Volume
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Create External Volume
    ####################################################################
    - name: Create External Volume
      hitachivantara.vspone_block.vsp.hv_external_volume:
        connection_info: "{{ connection_info }}"
        spec:
          external_storage_serial: "415045"
          external_ldev_id: 530

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
