---
- name: Hostgroup Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var_VSPF700.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Create hostgroup
    ####################################################################
    - name: Create hostgroup
      hitachivantara.vspone_block.vsp.hv_hg:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "hostgroup-server1"
          port: "CL3-E"
          host_mode: "WINDOWS_EXTENSION"
          ldevs: [72]
          wwns:
            - "50060e8028271342"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
