---
####################################################################
# Example : Hostgroup Playbook
####################################################################
- name: Hostgroup Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 1 : Create hostgroup
    ####################################################################
    - name: Create hostgroup
      hitachivantara.vspone_block.vsp.hv_hg:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "tc-ansible-hg"
          port: "CL7-C"
          host_mode: "LINUX"
          #host_mode_options: [54, 63]
          ldevs: [275]
          wwns:
            - "21000024ff86a664"
            #- "9876543210ABCDE1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result


