---
####################################################################
# Example : LDEV  Playbook
####################################################################
- name: Logical Device Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ###########################################################################
    # Task 6 : Create ldev with capacity saving and data_reduction_share
    ###########################################################################
    - name: Create ldev with capacity saving and data_reduction_share
      hitachivantara.vspone_block.vsp.hv_ldev:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          pool_id: 17
          size: "3GB"
          #capacity_saving: "compression_deduplication"
          #data_reduction_share: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result


