---
####################################################################
# Example :  Storage Port  Playbook
####################################################################
- name: Storage Port Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ###########################################################################################
    # Task Name : Change port speed and port security settings of the storage port by port id
    ###########################################################################################
    - name: Change port speed and port security settings of the storage port by port id
      hitachivantara.vspone_block.vsp.hv_storage_port:
        connection_info: "{{ connection_info }}"
        spec:
          port: "CL8-C"
          port_speed: "AUT" # Options: "AUT", "nG" - where n is a number and G can be omitted
          enable_port_security: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

