---
####################################################################
# Example :  Remote connection management Playbook
####################################################################
- name: Remote Connection add/remove/update
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ######################################################################################
    # Task 4 : Delete a remote connection
    ######################################################################################
    - name: Delete a remote connection
      hitachivantara.vspone_block.vsp.hv_remote_connection:
        connection_info: "{{ connection_info }}"
        state: absent
        spec:
          path_group_id: 1
          remote_storage_serial_number: "810005"
      register: result

    - name: Debug result
      ansible.builtin.debug:
        var: result

