---
######################################################################################
# Example :  Storage Pool Playbook
######################################################################################
- name: Storage Pool Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ######################################################################################
    # Task 2 : Create a storage pool using more details
    ######################################################################################
    - name: Create a storage pool using other details
      hitachivantara.vspone_block.vsp.hv_storagepool:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "ansible-pool-TC"
          type: "HDP"
          pool_volumes:
            - parity_group_id: "1-1"
              capacity: "100GB"
          warning_threshold_rate: 70
          depletion_threshold_rate: 80
          resource_group_id: 0
          should_enable_deduplication: false
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result


