---
####################################################################
# Example :  TrueCopy Playbook
####################################################################
- name: TrueCopy pair operations module
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    #######################################################################################
    # Task Name : Create a TrueCopy pair by specifying the provisioned_secondary_volume_id.
    # Use this playbook if the secondary volume is already attached to hostgroups or iscsi
    # targets, and there is no need to attach additional hostgroups or iscsi targets.
    #######################################################################################
    - name: Create TrueCopy pair with provisioned_secondary_volume_id
      hitachivantara.vspone_block.vsp.hv_truecopy:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        state: "present"
        spec:
          copy_group_name: "tc-copy-group-4"
          copy_pair_name: "tc-copy-pair-4"
          primary_volume_id: 321
          provisioned_secondary_volume_id: 338

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result


