---
######################################################################################
# Example :  TrueCopy Facts Playbook
######################################################################################
- name: TrueCopy Facts
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ######################################################################################
    # Task 1 : Get all TrueCopy pairs
    ######################################################################################
    - name: Get all TrueCopy pairs
      hitachivantara.vspone_block.vsp.hv_truecopy_facts:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result


