---
- name: Pre-Configuration Setup for GAD
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - pre_provision_vars_uf.yml
  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    rcu_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ####################################################################
    # Self-Contained Dependency: Fetch MCU Resource Group ID
    ####################################################################
    - name: Get Resource Group facts on MCU (Inline Dependency)
      hitachivantara.vspone_block.vsp.hv_resource_group_facts:
        connection_info: "{{ connection_info }}"
        spec:
          name: "{{ mcu_rg_name }}"
      register: inline_mcu_rg_facts

    - name: Set mcu_rg_id for standalone execution
      ansible.builtin.set_fact:
        mcu_rg_id: >-
          {{
            inline_mcu_rg_facts.ansible_facts.resource_groups[0].id | default(0)
          }}

    ####################################################################
    # Step 1: Check if Host Groups exist on their respective ports
    ####################################################################
    - name: Get Host Group facts from MCU
      hitachivantara.vspone_block.vsp.hv_hg_facts:
        connection_info: "{{ connection_info }}"
        spec:
          port_ids: ["{{ item.port }}"]
          name: "{{ item.name }}"
      loop: "{{ mcu_host_groups }}"
      register: mcu_hg_facts_results

    - name: Debug the MCU HostGroup
      ansible.builtin.debug:
        var: mcu_hg_facts_results

    ####################################################################
    # Step 2: Create Host Groups without LDEVs
    ####################################################################
    - name: Create Host Groups without LDEVs
      hitachivantara.vspone_block.vsp.hv_hg:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "{{ item.name }}"
          port_id: "{{ item.port }}"
          host_mode: "{{ item.host_mode }}"
          wwns: "{{ item.wwns }}"
      loop: "{{ mcu_host_groups }}"
      loop_control:
        index_var: hg_index
      when: >-
        mcu_hg_facts_results.results[hg_index].ansible_facts.hostGroups is not defined or
        (mcu_hg_facts_results.results[hg_index].ansible_facts.hostGroups | length == 0)
      register: hostgroup_creation_results

    ####################################################################
    # Step 3: Migrate Host Groups to Target Resource Group
    ####################################################################
    - name: Move Host Groups to the Target Resource Group
      hitachivantara.vspone_block.vsp.hv_resource_group:
        connection_info: "{{ connection_info }}"
        state: present
        spec:
          state: "add_resource"
          name: "{{ mcu_rg_name }}"
          host_groups:
            - port: "{{ item.port }}"
              name: "{{ item.name }}"
      loop: "{{ mcu_host_groups }}"
      loop_control:
        index_var: hg_index
      when: >
        (mcu_hg_facts_results.results[hg_index].ansible_facts.hostGroups is not defined) or
        (mcu_hg_facts_results.results[hg_index].ansible_facts.hostGroups | length == 0) or
        (mcu_hg_facts_results.results[hg_index].ansible_facts.hostGroups[0].resource_group_id | default(0) != (mcu_rg_id | int))
